---
resources:
  - ../../base
  - ../dashboard

patches:
  - target:
      kind: ConfigMap
      name: topology
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: topology
