---
environment:
  openshift: true

topology:
  nodePools:
    default:
      gpuProduct: NVIDIA-H200
      gpuCount: 8
      gpuMemory: 143771
      otherDevices:
        - name: nvidia.com/mig-1g.18gb
          count: 16
        - name: nvidia.com/mig-2g.35gb
          count: 8
        - name: nvidia.com/mig-3g.71gb
          count: 8
  nodePoolLabelKey: run.ai/simulated-gpu-node-pool
  migStrategy: mixed

devicePlugin:
  image:
    repository: quay.io/eformat/fake-gpu-operator-device-plugin
    tag: latest

migFaker:
  enabled: true
  image:
    repository: quay.io/eformat/fake-gpu-operator-mig-faker
    tag: latest

statusUpdater:
  image:
    repository: quay.io/eformat/fake-gpu-operator-status-updater
    tag: latest
