---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfd
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-nfd
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: https://github.com/eformat/fake-gpu-booking.git
    targetRevision: main
    path: acm/base/charts/nfd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
